# test this goreleaser config with:
# - cd cloud-connector
# - goreleaser --clean --snapshot --config .goreleaser.yaml
version: 2
project_name: outsystemscc
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: outsystemscc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
